package com.creatorstudio.backend.service;

import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.HashMap;
import java.util.Map;

@Service
public class OllamaService {

    private final RestTemplate restTemplate = new RestTemplate();

    private static final String OLLAMA_URL =
            "http://localhost:11434/api/generate";

    public String generateScript(String story) {

        String prompt = """
    Create a complete screenplay.

    IMPORTANT:
    - Do not explain your thinking.
    - Do not show reasoning.
    - Return only the screenplay.

    Story:
    %s

    Create exactly 5 scenes.

    For each scene include:

    Location:
    Characters:
    Action:
    Dialogue:
    Emotion:

    Add a suitable title.

    Return only the final screenplay.
    """.formatted(story);

        Map<String, Object> request = new HashMap<>();
        request.put("model", "llama3.2:3b");
        request.put("prompt", prompt);
        request.put("stream", false);

        Map<String, Object> options = new HashMap<>();
        options.put("num_predict", 800);
        request.put("options", options);

        Map<String, Object> response =
                restTemplate.postForObject(
                        OLLAMA_URL,
                        request,
                        Map.class
                );

        System.out.println("OLLAMA RESPONSE:");
        System.out.println(response);

        if (response == null) {
            throw new RuntimeException("No response received from Ollama");
        }

        String result = "";

        if (response.get("response") != null) {
            result = response.get("response").toString();
        }

        if (result == null || result.isBlank()) {
    result = "No screenplay generated by Ollama.";
}

        return result;
    }
}